Feature: Adding measurement_unit & unit_multiplier to send to clerk
vtex-apps/clerkio-integration pull request #31
Opened 2023-01-19 08:44 UTC by briand3v

#### What problem is this solving?
- Adding two more attributes that is needed to send to clerk

- In our integration with clerk we need this additional attributes in order to us to complete the full display of product info in our web.

2023-01-19 08:52 UTC, briand3v commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [ ]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2023-01-19 08:56 UTC, briand3v commented
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x ]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

2023-01-19 10:14 UTC, Fbenitez97 commented
@edyespinal si le puedes echar un vistazo al PR de Brian cuanto antes por favor 👀

2023-01-19 10:31 UTC, edyespinal approved these changes

2023-01-19 10:33 UTC, edyespinal requested changes
Everything looks good.

Let's just update the CHANGELOG so we can merge.

2023-01-19 10:53 UTC, edyespinal commented
One other thing to note here is that this PR is pointing to the `hotfix/ametller`.
This branch contains changes that are part of a POC and are not ready to production and might not be published at all.

I would recommend pointing this PR to  `main` instead.

2023-01-19 11:30 UTC, briand3v commented
Then I should make new PR from base main and make the PR? Because now I see that is getting others commits related with this branch **hotfix/ametller** which this PR is based (branch where there are changes that we need, this is why vtex gave us this version to us).
Also then also to point in manifest version to 1.1.5 ?

2023-01-19 11:43 UTC, edyespinal commented
Ok, I see.

The changes you are making are related to the POC for Ametller then?
In that case, it's ok to point it to the original branch (`hotfix/ametller`).
Regarding the version, since this version will not be deployed for the moment, I think you should keep the version as `1.1.7-hkignore-beta.1`.

2023-01-19 11:48 UTC, briand3v commented
Ok! Perfect! Yes it is! Then I will switch it up again to hotfix/ametller 😉.
And change the version to 1.1.7-hkignore-beta.1 in manifest.

Also then should I change back the changelog to this version ?

2023-01-19 12:20 UTC, edyespinal commented
You don't need to add the version to the changelog.
The version gets added when the app is published.

I already updated the changelog for this.

2023-01-19 17:35 UTC, edyespinal approved these changes

2023-01-20 08:25 UTC, briand3v commented
Thanks for accepting this PR. If you can merge this PR as soon is possible would be nice for us. Thank you :)

2023-01-20 10:27 UTC, merged